# Introduction to NumPy

This notebook covers fundamental NumPy operations used in data processing and machine learning.


In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [7]:
arr.shape

arr.dtype


dtype('int64')

In [9]:
arr + 5

array([15, 25, 35, 45, 55])

In [10]:
arr * 2 

array([ 20,  40,  60,  80, 100])

In [12]:
matrix = ([[0,1,2],
          [3,4,5]])

matrix

[[0, 1, 2], [3, 4, 5]]

In [18]:
matrix[0]
matrix[1]

[3, 4, 5]

## Observations

- NumPy arrays allow fast numerical operations.
- Broadcasting makes element-wise operations efficient.
- 2D arrays are commonly used to represent datasets and feature matrices.
